$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
useGitignore: true
files:
  - '**'
  - '.*'
  - '.**/*'
  - '!.git/**'
ignorePaths:
  - pnpm-lock.yaml
dictionaries:
  - npm
  - softwareTerms
  - fullstack
  - html
  - css
words:
  - bradlc
  - dbaeumer
  - doctag
  - dotenvx
  - lowlight
  - nelsonlai
  - nelsonlaidev
  - paralleldrive
  - pilcrow
  - shiki
  - umami
